language: python

services:
  - mongodb

python:
  - 2.6
  - 2.7
  - pypy

env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4
  - DJANGO=1.5

matrix:
  allow_failures:
    - env: DJANGO=1.4
    - env: DJANGO=1.5

before_install:
  - pip install --use-mirrors Django==$DJANGO mongokit

install:
  - python setup.py install

script:
  - DJANGO_SETTINGS_MODULE=test_settings python django_mongokit/tests.py
